//
//  SyntaxTree.swift
//  Parser
//
//  Created by Ulf Akerstedt-Inoue on 2023/09/06.
//  Copyright © 2023 hakkabon software. All rights reserved.
//

import Foundation

/// A tree that can store different types of values in its leafs.
///
/// - leaf: Leaf node
/// - node: Internal node with with an arbitrary list of child elements (derivations).
/// - empty: An empty tree.
public enum SyntaxTree<Node: Hashable & Equatable, Leaf: Hashable & Equatable> {
    /// A leaf storing a leaf element
    case leaf(Leaf)

    /// A node with an arbitrary list of child elements (derivations).
    indirect case node(Node, children: [SyntaxTree<Node, Leaf>])
    
    /// Represents the initial state or a placeholder.
    /// Useful for the bottom of the parser stack.
    case empty
}

extension SyntaxTree: Hashable {
    
    /// Making `SyntaxTree` conform to `Hashable` enables indexing, caching, and storing
    /// syntax trees in `Set` collections.
    public func hash(into hasher: inout Hasher) {
        switch self {
        case .leaf(let t):
            hasher.combine(t.hashValue)
        case .node(let n, children: let c):
            hasher.combine(n.hashValue)
            hasher.combine(c.hashValue)
        case .empty:
            hasher.combine(0)
        }
    }
}

public extension SyntaxTree {
    
    /// Creates a new syntax tree node with a given node and a list of children
    ///
    /// - Parameters:
    ///   - node: Root node
    ///   - children: Children of the root node
    init(node: Node, children: [SyntaxTree<Node, Leaf>]) {
        self = .node(node, children: children)
    }
    
    /// Creates a new syntax tree with a given root node and no children
    ///
    /// - Parameter node: Root node
    init(node: Node) {
        self = .node(node, children: [])
    }
    
    /// Creates a new syntax tree with a given leaf value
    ///
    /// - Parameter value: Leaf value
    init(value: Leaf) {
        self = .leaf(value)
    }
}

public extension SyntaxTree {
    
    /// Returns the root node of the tree or nil if no root node exists
    var root: Node? {
        guard case .node(let node, children: _) = self else {
            return nil
        }
        return node
    }
    
    /// Returns the value stored in the current node if the current node is a leaf. Otherwise, nil is returned
    var leaf: Leaf? {
        guard case .leaf(let leaf) = self else {
            return nil
        }
        return leaf
    }
    
    /// Returns the direct children of the root node
    var children: [SyntaxTree<Node, Leaf>]? {
        guard case .node(_, children: let children) = self else {
            return nil
        }
        return children
    }
    
    /// Child Node Access via Subscripts
    /// Accessing children of an enum-based tree structure.
    subscript(index: Int) -> SyntaxTree<Node, Leaf>? {
        guard case .node(_, let children) = self, children.indices.contains(index) else { return nil }
        return children[index]
    }
}

public extension SyntaxTree {

	/// Generates a new syntax tree by applying the transform function to every inner node of the tree.
	///
	/// - Parameter transform: Transform function
	/// - Returns: A tree generated by applying the transform function to every inner node.
	func mapNodes<Result>(_ transform: (Node) throws -> Result) rethrows -> SyntaxTree<Result, Leaf> {
		switch self {
		case .leaf(let leaf):
			return .leaf(leaf)
			
		case let .node(node, children: children):
			return try .node(transform(node), children: children.map{ try $0.mapNodes(transform) } )

        case .empty:
            return .empty
		}
	}
	
	/// Generates a new syntax tree by applying the transform function to every leaf of the tree.
	///
	/// - Parameter transform: Transform function
	/// - Returns: A tree generated by applying the transform function to every leaf value
	func mapLeafs<Result>(_ transform: (Leaf) throws -> Result) rethrows -> SyntaxTree<Node, Result> {
		switch self {
		case .leaf(let leaf):
			return try .leaf(transform(leaf))
			
		case let .node(node, children: children):
			return try .node(node, children: children.map{ try $0.mapLeafs(transform) } )

        case .empty:
            return .empty
		}
	}
	
	/// All leafs of the tree
	var leafs: [Leaf] {
		switch self {
		case .leaf(let leaf):
			return [leaf]
			
		case .node(_, children: let children):
			return children.flatMap{$0.leafs}

        case .empty:
            return []
		}
	}
	
	/// Filters the tree by removing all nodes and their corresponding subtrees if the given predicate is false
	///
	/// - Parameter predicate: Predicate to filter the tree
	/// - Returns: A tree generated by filtering out nodes for which the predicate returned false
	func filter(_ predicate: (Node) throws -> Bool) rethrows -> SyntaxTree<Node, Leaf>? {
		switch self {
		case .leaf(let element):
			return .leaf(element)
			
		case let .node(node, children: children) where try predicate(node):
			return try .node(node, children: children.compactMap{try $0.filter(predicate)})
			
		case .node(_, children: _):
			return nil

        case .empty:
            return nil
		}
	}
	
    /// Replace a node with its children if the given closure returns true.
    /// This operation is usually described as "flattening tree operation".
	///
	/// - Parameter predicate: Determines if a node should be inlined
	/// - Returns: A tree generated by flattening nodes determined by the given predicate
	func flattened(where predicate: (Node) throws -> Bool) rethrows -> [SyntaxTree<Node, Leaf>] {
		switch self {
		case .leaf:
			return [self]
			
		case let .node(node, children: children) where try predicate(node):
            return try children.flatMap{try $0.flattened(where: predicate)}
			
		case let .node(node, children: children):
            return try [.node(node, children: children.flatMap{try $0.flattened(where: predicate)})]

        case .empty:
            return []
		}
	}
	
	/// Simplifies trees in syntax tree by collapsing chain nodes that have exactly one child.
	///
	/// - Returns: Tree generated by simplifying the current tree (unary branch collapsed)
	func simplified() -> SyntaxTree<Node, Leaf> {
		switch self {
		case .node(_, children: let children) where children.count == 1:
			let child = children[0]
			if case .leaf = child {
				return self
			} else {
				return child.simplified()
			}
			
		case let .node(node, children: children):
			return .node(node, children: children.map{ $0.simplified() })
			
		default:
			return self
		}
	}
	
	/// Returns all nodes which match the given predicate.
	///
	///
	/// - Parameter predicate: Predicate to match
	/// - Returns: A collection of nodes which match the given predicate
	func allNodes(where predicate: (Node) throws -> Bool) rethrows -> [SyntaxTree<Node, Leaf>] {
		switch self {
		case .leaf:
			return []
			
		case let .node(node, children: children) where try predicate(node):
			return try [self] + children.flatMap{try $0.allNodes(where: predicate)}
			
		case .node(_, children: let children):
			return try children.flatMap{ try $0.allNodes(where: predicate) }

        case .empty:
            return []
		}
	}
}

public extension SyntaxTree where Leaf == Range<String.Index> {
    
    /// Maps the tree's leaf ranges to actual substrings from the source document.
    func resolved(in source: String) -> SyntaxTree<Node, Substring> {
        return self.mapLeafs { range in
            source[range]
        }
    }
}

extension SyntaxTree: Equatable {
    
    /// Determines if two syntax trees are equal to each other.
    /// This function returns true, if both trees have the same structure, equal inner nodes and equal leafs
    ///
    /// - Parameters:
    ///   - lhs: First tree to compare
    ///   - rhs: Second tree to compare
    /// - Returns: A boolean value indicating whether the provided trees are equal to each other
    public static func == (lhs: SyntaxTree<Node, Leaf>, rhs: SyntaxTree<Node, Leaf>) -> Bool {
        switch (lhs, rhs) {
        case let(.leaf(lLeaf), .leaf(rLeaf)):
            return lLeaf == rLeaf
            
        case (.node(let lKey, children: let lChildren), .node(let rKey, children: let rChildren)):
            return lKey == rKey && lChildren.count == rChildren.count && !zip(lChildren, rChildren).map(==).contains(false)
            
        default:
            return false
        }
    }
}

extension SyntaxTree: CustomStringConvertible {

    /// Pretty print as a real tree
    public var description: String {
        return SyntaxTreePrinter.print(self)
    }
}
